url: "https://jira.codegold79.com"
project: "TMG"
username: "codegold"
password: "JIRA_PASSWORD"
issueKey: "TMG-808"
summary: "Issue 11 (Dec 12, 2022)"
description: "12/15/22: Issue 11 updated with editorial changes."
